
include: package:flutter_lints/flutter_lints.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_single_quotes
    - sort_child_properties_last

analyzer:
  exclude:
    - "**/*.g.dart"
  language:
    strict-casts: true
    strict-raw-types: true
