name: neon_bmi_calculator
description: A neon-themed Flutter BMI calculator web application that provides interactive health insights and personalized tracking.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.2.0
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  just_audio: ^0.10.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/icon.png
  android: true
  ios: true
